// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkOrccQmNyC8iiceS3yZadZV-XFagF9ug',
    appId: '1:892037478328:web:026b879c5fa02d71b0c14d',
    messagingSenderId: '892037478328',
    projectId: 'chat-app-432fa',
    authDomain: 'chat-app-432fa.firebaseapp.com',
    storageBucket: 'chat-app-432fa.appspot.com',
    measurementId: 'G-73BTH37WK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KAFo3s60j0lMfBV3FiWczrefoc_wPmc',
    appId: '1:892037478328:android:7a261da617d0d791b0c14d',
    messagingSenderId: '892037478328',
    projectId: 'chat-app-432fa',
    storageBucket: 'chat-app-432fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeMwzOW1qczSp1hsvlNddPx9e_hWoXkE',
    appId: '1:892037478328:ios:b7f9edd182a54004b0c14d',
    messagingSenderId: '892037478328',
    projectId: 'chat-app-432fa',
    storageBucket: 'chat-app-432fa.appspot.com',
    iosClientId: '892037478328-d1mhmrclmugbsp0s2g394v11grils4g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );
}
